NAMED_CORRIDORS = {
    'Airport New South Road',
    'Bannerghata Road',
    'Bellary Road 1',
    'Bellary Road 2',
    'CBD 1',
    'CBD 2',
    'Hennur Main Road',
    'Hosur Road',
    'IRR(Thanisandra road)',
    'Magadi Road',
    'Mysore Road',
    'ORR East 1',
    'ORR East 2',
    'ORR North 1',
    'ORR North 2',
    'ORR West 1',
    'Old Airport Road',
    'Old Madras Road',
    'Tumkur Road',
    'Varthur Road',
    'West of Chord Road',
}

NON_CORRIDOR_ROADS = {
    '100 Feet Road, Kanteerava Studio Circle': {'zone': 'Central Zone 1', 'junction': 'BM ShriJunc(CMH-100FtRd)Junc', 'lat': 13.021, 'lng': 77.5283},
    '10th Main Road, Achaiah Chetty Layout': {'zone': 'South Zone 2', 'junction': 'MekhriCircle', 'lat': 12.9367, 'lng': 77.5842},
    '11th Cross Road, Acharya Sri Ramanuja Circle': {'zone': 'West Zone 2', 'junction': 'Geethanjali jn', 'lat': 12.99, 'lng': 77.5883},
    '11th Main Road, Sri Aurobindo Circle': {'zone': 'South Zone 1', 'junction': 'Arbindo Circle', 'lat': 12.9202, 'lng': 77.5859},
    '12th Cross Road, Lakksandra Extension': {'zone': 'West Zone 2', 'junction': 'PuttammaChoultryNagarbhavi', 'lat': 12.9471, 'lng': 77.5974},
    '13th Cross Road, Bashyam Circle': {'zone': 'South Zone 2', 'junction': 'BhashyamCircle-SadashivNagar', 'lat': 12.9294, 'lng': 77.5982},
    '1st Cross Road, Koramangala Water Tank Junction': {'zone': 'South Zone 2', 'junction': 'KoramangalaWaterTankJunc', 'lat': 12.9625, 'lng': 77.6013},
    '1st Main Road, Sri Vijayamaruthi Circle': {'zone': 'East Zone 2', 'junction': 'AyyappaTempleJunc', 'lat': 13.0117, 'lng': 77.5849},
    '24th Main Road, Sarakki Agrahara': {'zone': 'South Zone 1', 'junction': 'JP Nagar 9th cross-24th main jn', 'lat': 12.9062, 'lng': 77.5857},
    '27th Cross Road, Dr BR Ambedkar Circle': {'zone': 'East Zone 1', 'junction': 'Unknown', 'lat': 12.9382, 'lng': 77.7467},
    '2nd Cross Road, MTB Area': {'zone': 'South Zone 1', 'junction': 'toll gate mysore road', 'lat': 12.9186, 'lng': 77.5895},
    '2nd Main Road, Abdul Patel Syed Layout': {'zone': 'North Zone 2', 'junction': 'HebbalFlyoverJunc', 'lat': 13.0334, 'lng': 77.5817},
    '3rd Cross Road, Bommanahalli Circle': {'zone': 'Central Zone 2', 'junction': 'ArakereGateJunc', 'lat': 12.9896, 'lng': 77.5735},
    '3rd Main Road, Chakkasandra': {'zone': 'South Zone 2', 'junction': 'NTTF JunctionPeenya', 'lat': 13.0229, 'lng': 77.5896},
    '46th Cross Road, Sri Aurobindo Circle': {'zone': 'South Zone 1', 'junction': 'Arbindo Circle', 'lat': 12.917, 'lng': 77.5853},
    '4th Cross Road, Papareddypalya Circle': {'zone': 'West Zone 1', 'junction': 'AyyappaTempleJunc', 'lat': 12.9934, 'lng': 77.6056},
    '4th Main Road, Shri Satya Sai Circle': {'zone': 'North Zone 2', 'junction': 'BigBazaarJunction(OldMadrasRd)', 'lat': 12.9641, 'lng': 77.5803},
    '5th Cross Road, Uday Nagar': {'zone': 'South Zone 2', 'junction': 'BMTCJunction-K H Road', 'lat': 12.9598, 'lng': 77.6208},
    '5th Main Road, Anandgiri Extension': {'zone': 'West Zone 1', 'junction': 'BrigadeMillenium', 'lat': 12.9611, 'lng': 77.5807},
    '60 Feet Road, KK Layout': {'zone': 'West Zone 1', 'junction': 'Unknown', 'lat': 12.9688, 'lng': 77.5037},
    '6th Main Road, BDA Industrial Suburb': {'zone': 'South Zone 2', 'junction': 'Unknown', 'lat': 12.8994, 'lng': 77.6222},
    '7th Cross Road, BDA Junction': {'zone': 'South Zone 2', 'junction': 'BDA Junctio-Koramangala', 'lat': 12.9225, 'lng': 77.6037},
    '7th Main Road, Balaji Layout': {'zone': 'North Zone 2', 'junction': 'BTM16thMain-ORR Junc', 'lat': 12.9854, 'lng': 77.5484},
    '80 Feet Ring Road, Harikara Vidvan Sri R Gururajulu Naidu Circle': {'zone': 'West Zone 1', 'junction': 'Dr RajkumarRd-10thCrossRdJunc', 'lat': 12.998, 'lng': 77.5541},
    '80 Feet Road, Block 2': {'zone': 'South Zone 1', 'junction': '17th Mn 1st Crs Aishwarya Stores Jn', 'lat': 12.9934, 'lng': 77.5764},
    '8th Cross Road, RR Palace': {'zone': 'North Zone 1', 'junction': 'Unknown', 'lat': 13.0562, 'lng': 77.6025},
    '9th Cross Road, Kaniyar Colony': {'zone': 'Central Zone 2', 'junction': 'SirsiCircle', 'lat': 12.9355, 'lng': 77.5709},
    '9th Main Road, Shri Satya Sai Circle': {'zone': 'Unknown', 'junction': 'Unknown', 'lat': 12.9276, 'lng': 77.5836},
    'Adugodi Road, Krupanidhi College Junction': {'zone': 'South Zone 2', 'junction': 'Krupanidhi College', 'lat': 12.9353, 'lng': 77.6241},
    'Amrutha College Road, Sri Venkateshwara Circle': {'zone': 'South Zone 2', 'junction': 'Unknown', 'lat': 12.8786, 'lng': 77.6721},
    'Ashok Nagar Road, Ashirwadam Junction': {'zone': 'Central Zone 1', 'junction': 'BucheryJunction', 'lat': 12.9626, 'lng': 77.6143},
    'Assayee Road, Sham Mansion Apartment': {'zone': 'Unknown', 'junction': 'Unknown', 'lat': 12.9939, 'lng': 77.6191},
    'Banashankari Road, Sarbandapalya': {'zone': 'West Zone 2', 'junction': 'BanashankariBusStandJunc', 'lat': 12.917, 'lng': 77.5703},
    'Banaswadi Road, Gopalan Signature Mall': {'zone': 'Central Zone 1', 'junction': 'Unknown', 'lat': 12.9937, 'lng': 77.6619},
    'Basavanagudi Road, Cauvery Circle': {'zone': 'Central Zone 2', 'junction': 'South end circle', 'lat': 12.9436, 'lng': 77.5752},
    'Begur Main Road, Alpine Park Apartment': {'zone': 'South Zone 2', 'junction': 'Bommanahalli', 'lat': 12.898, 'lng': 77.6264},
    'Bellandur Road, Kasavanahalli': {'zone': 'East Zone 1', 'junction': 'Unknown', 'lat': 12.9082, 'lng': 77.6751},
    'Broadway Road, Chandni Chowk': {'zone': 'Central Zone 2', 'junction': 'Unknown', 'lat': 12.9858, 'lng': 77.6051},
    'Byatarayanapura Road, Nagarabavi Circle': {'zone': 'West Zone 1', 'junction': 'Nagarbhavi', 'lat': 12.958, 'lng': 77.519},
    'CV Raman Road, SBD Township Sector B': {'zone': 'West Zone 2', 'junction': 'YeshwanthpuraCircle', 'lat': 13.0161, 'lng': 77.5615},
    'Chamarajpet Road, Sangolli Rayanna Circle': {'zone': 'Central Zone 2', 'junction': 'ShantalaJunction', 'lat': 12.9747, 'lng': 77.5704},
    'Chikkabanavara Road, Nagasandra': {'zone': 'North Zone 2', 'junction': 'BagalakunteCrossJunction', 'lat': 13.0496, 'lng': 77.5011},
    'Chikkajala Road, Phase 2A': {'zone': 'Unknown', 'junction': 'Unknown', 'lat': 13.1608, 'lng': 77.6526},
    'City Market Road, Santhusapete': {'zone': 'Central Zone 2', 'junction': 'Minerva Circle', 'lat': 12.955, 'lng': 77.5804},
    'Cubbon Park Road, Krishna Rajendra Circle': {'zone': 'Central Zone 2', 'junction': 'K R Circle', 'lat': 12.9766, 'lng': 77.5879},
    'Devanahalli Airport Road, Sri Kanakadasa Circle': {'zone': 'Unknown', 'junction': 'DevanahalliCrossJunc', 'lat': 13.2435, 'lng': 77.7071},
    'Dhanvanthri Road, Ayurvedic Hospital Junction': {'zone': 'Central Zone 2', 'junction': 'KhodaysCircle(DV UrsCircle)', 'lat': 12.9796, 'lng': 77.5728},
    'Dinnur Main Road, Southern Residency Apartment': {'zone': 'Unknown', 'junction': 'Unknown', 'lat': 13.0219, 'lng': 77.603},
    'Doddaballapur Main Road, East Colony': {'zone': 'North Zone 2', 'junction': 'Unknown', 'lat': 13.1255, 'lng': 77.574},
    'Dr Ambedkar Road, Krishna Rajendra Circle': {'zone': 'Central Zone 2', 'junction': 'K R Circle', 'lat': 12.9802, 'lng': 77.593},
    'Dr MH Ambarish Road, C Ranga Swamy Circle': {'zone': 'Central Zone 2', 'junction': 'BasaweshwaraCircle', 'lat': 12.9839, 'lng': 77.5826},
    'Dr Rajgopal Road, Ashwath Nagar': {'zone': 'North Zone 2', 'junction': 'Unknown', 'lat': 13.0273, 'lng': 77.5795},
    'Dr Rajkumar Puniya Bhoomi Road, Block 6': {'zone': 'West Zone 1', 'junction': 'KadirenahalliJunction', 'lat': 12.9604, 'lng': 77.5369},
    'Dr TCM Royan Road, Cottonpet Circle': {'zone': 'Central Zone 2', 'junction': 'ShantalaJunction', 'lat': 12.9728, 'lng': 77.569},
    'Electronic City Road, Pramuk Aqua Heights': {'zone': 'South Zone 1', 'junction': 'VeerasandraGateJunction', 'lat': 12.84, 'lng': 77.6762},
    'Electronics City Flyover, Bommanahalli Circle': {'zone': 'South Zone 2', 'junction': 'ElectronicCityGate-2Junc', 'lat': 12.8794, 'lng': 77.646},
    'Halasur Road, Agaram': {'zone': 'Central Zone 1', 'junction': 'CommandoHospitalJunc', 'lat': 12.9623, 'lng': 77.6297},
    'Halasuru Gate Road, Ashirwadam Junction': {'zone': 'Central Zone 2', 'junction': 'BloodBankCircle', 'lat': 12.9722, 'lng': 77.5874},
    'High Ground Road, Karnataka Bhavan Junction': {'zone': 'Central Zone 2', 'junction': 'CID-CarltonHouseJunc', 'lat': 12.9832, 'lng': 77.586},
    'Hoodi Main Road, ESI Road Junction': {'zone': 'East Zone 1', 'junction': 'Unknown', 'lat': 12.9879, 'lng': 77.711},
    'Hulimavu Road, Anjaneya Swami Circle': {'zone': 'South Zone 1', 'junction': 'Unknown', 'lat': 12.8761, 'lng': 77.6165},
    'JP Nagar Road, Sri Aurobindo Circle': {'zone': 'South Zone 2', 'junction': 'KanakapuraRd-RingRdJunction', 'lat': 12.9122, 'lng': 77.5847},
    'Jalahalli Road, Gangamma Circle': {'zone': 'North Zone 1', 'junction': 'GangammagudiJunc', 'lat': 13.0521, 'lng': 77.5466},
    'Jayamahal Main Road, Enayathulla Mehkri Circle': {'zone': 'North Zone 2', 'junction': 'MekhriCircle', 'lat': 13.0144, 'lng': 77.5854},
    'Jayanagara Road, MTB Area': {'zone': 'South Zone 1', 'junction': '28thMainJayanagarJunc', 'lat': 12.9186, 'lng': 77.5873},
    'Jeevanbheemanagar Road, Thimmaiah Reddy Colony': {'zone': 'Central Zone 1', 'junction': 'BEML GateJunc(SuranjandasRd)', 'lat': 12.9667, 'lng': 77.6599},
    'Jnanabharathi Road, Kengunte Circle': {'zone': 'West Zone 1', 'junction': 'Ring road-Near Kengunte Junction', 'lat': 12.9638, 'lng': 77.505},
    'K.R. Pura Road, Zero Tolerance Junction': {'zone': 'East Zone 2', 'junction': 'Devasandra(k r puram)', 'lat': 13.0162, 'lng': 77.7088},
    'KG Halli Road, Bilal Nagar': {'zone': 'North Zone 1', 'junction': 'PotteryCircle', 'lat': 13.0108, 'lng': 77.6153},
    'KH Road, Ashirwadam Junction': {'zone': 'Central Zone 2', 'junction': 'BMTCJunction-K H Road', 'lat': 12.9586, 'lng': 77.5932},
    'KR Main Road, Professor P Shivshankar Circle': {'zone': 'Central Zone 2', 'junction': 'Shivashankara circle', 'lat': 12.9581, 'lng': 77.5739},
    'KS Layout Road, Muneshwara Nagar': {'zone': 'South Zone 1', 'junction': 'UttarahalliJunction', 'lat': 12.907, 'lng': 77.5496},
    'Kamakshipalya Road, Sattva Anugraha': {'zone': 'West Zone 1', 'junction': 'Unknown', 'lat': 12.9884, 'lng': 77.4951},
    'Kempegowda Road, Skyline Retreat': {'zone': 'North Zone 1', 'junction': 'EliteJunc', 'lat': 12.9753, 'lng': 77.5799},
    'Kengeri Main Road, Kengunte Circle': {'zone': 'West Zone 1', 'junction': 'RingRoad-UllalJunction', 'lat': 12.9574, 'lng': 77.5032},
    'Kengeri Road, Ideal Home Township': {'zone': 'West Zone 1', 'junction': 'RajeshwariJunc', 'lat': 12.9286, 'lng': 77.5167},
    'Kodigehalli Road, Pillappa Layout': {'zone': 'North Zone 1', 'junction': 'Unknown', 'lat': 13.0621, 'lng': 77.5767},
    'Konanakunte Main Road, Jagathguru Shri Sivaratripura Circle': {'zone': 'South Zone 1', 'junction': 'BanashankariBusStandJunc', 'lat': 12.898, 'lng': 77.5719},
    'Kumar Krupa Road, Make In India Circle': {'zone': 'Central Zone 2', 'junction': 'ShivandaCircle', 'lat': 12.9906, 'lng': 77.5822},
    'Lalbagh Main Road, Dr Sri Shantaveera Swami Circle': {'zone': 'Central Zone 2', 'junction': 'PurnimaTheaterJunc', 'lat': 12.9561, 'lng': 77.5858},
    'MBT Road, Block 5 Stage 1': {'zone': 'North Zone 1', 'junction': 'Nagavara-ORR Junction', 'lat': 13.0316, 'lng': 77.6431},
    'MS Ramaiah Road, BEL Circle': {'zone': 'North Zone 1', 'junction': 'BEL Circle', 'lat': 13.0431, 'lng': 77.5571},
    'Madiwala Road, Krishna Reddy Layout': {'zone': 'South Zone 2', 'junction': 'Unknown', 'lat': 12.9005, 'lng': 77.6261},
    'Magadi Road (Local), Okalipuram Junction': {'zone': 'Central Zone 2', 'junction': 'KarnatakaBhavanJunction', 'lat': 12.9821, 'lng': 77.5643},
    'Mahadevapura Road, Sadaramangala Industrial Area': {'zone': 'East Zone 1', 'junction': 'BigBazaar(Whitefield)Junc', 'lat': 12.9924, 'lng': 77.735},
    'Malleshwaram Road, Sri Maramma Temple Circle': {'zone': 'Central Zone 1', 'junction': 'MargosaRd-18thCrossJunc', 'lat': 13.0009, 'lng': 77.5713},
    'Mico Layout Road, 29th BTM Road Junction': {'zone': 'South Zone 2', 'junction': 'Marigowda-TavarkereRdJunc', 'lat': 12.9186, 'lng': 77.6089},
    'Millers Road, Chavundaraya Circle': {'zone': 'Central Zone 2', 'junction': 'ChaudrayaCircle/UdayaTVCircle(CantonmentJunc)', 'lat': 12.9932, 'lng': 77.5954},
    'Mumbai Bengaluru Highway, Nadaprabhu Kempegowda Circle': {'zone': 'West Zone 1', 'junction': 'GokuldasImagesJunc', 'lat': 13.0489, 'lng': 77.4971},
    'Muthsandra Main Road, KSRTC Travel House Junction': {'zone': 'East Zone 1', 'junction': 'Unknown', 'lat': 12.9425, 'lng': 77.7473},
    'NICE Road, Madavara': {'zone': 'West Zone 1', 'junction': 'ElectronicCityGate-2Junc', 'lat': 12.9459, 'lng': 77.4754},
    'Nagarabhavi Main Road, Block 12': {'zone': 'West Zone 1', 'junction': 'Nagarbhavi', 'lat': 12.9603, 'lng': 77.5143},
    'Netaji Road, Puttanna Junction': {'zone': 'North Zone 1', 'junction': 'Bamboobazar(Shivajinagar)', 'lat': 12.997, 'lng': 77.6082},
    'Nice Road, Sunbeam 1': {'zone': 'Unknown', 'junction': 'Unknown', 'lat': 13.0569, 'lng': 77.4776},
    'Padmabhushan Dr RK Srikantan Road, Kalpataru Kalpavriksha': {'zone': 'Central Zone 2', 'junction': 'KrishnaFlourMill', 'lat': 12.9848, 'lng': 77.5747},
    'Padmasri CK Venkata Ramaiah Road, Sadashivanagar Junction': {'zone': 'West Zone 2', 'junction': 'ISRO Junction-NewBEL Rd', 'lat': 13.0313, 'lng': 77.57},
    'Peenya Road, Sobha Garrison': {'zone': 'West Zone 1', 'junction': 'Peenya2ndStageBusStand', 'lat': 13.0466, 'lng': 77.502},
    'Pulikeshinagar Road, Sindhi Colony': {'zone': 'North Zone 1', 'junction': 'SindhiColonyJunction', 'lat': 12.9949, 'lng': 77.6149},
    'RT Nagar Road, Vasanth Enclave': {'zone': 'Central Zone 2', 'junction': 'PriyadarshiniHotel,Jayamahal,RT Nagar', 'lat': 13.0058, 'lng': 77.595},
    'Rajajinagar Road, Narasimhaswamy Layout': {'zone': 'West Zone 1', 'junction': 'FTI Junction(KanteeravaStudio)', 'lat': 13.0093, 'lng': 77.5299},
    'SM Road, Patel Shamanna Layout': {'zone': 'North Zone 2', 'junction': 'JalahalliCross(SM Circle)', 'lat': 13.0547, 'lng': 77.535},
    'Sadashivanagar Road, Sadashivanagar Junction': {'zone': 'West Zone 2', 'junction': 'SadashivnagarJunc', 'lat': 13.0145, 'lng': 77.5727},
    'Sankey Road, RV Layout': {'zone': 'Central Zone 2', 'junction': 'Unknown', 'lat': 12.9926, 'lng': 77.5853},
    'Sarjapur Marathahalli Road, Koramangala Water Tank Junction': {'zone': 'South Zone 2', 'junction': 'KoramangalaWaterTankJunc', 'lat': 12.9275, 'lng': 77.6212},
    'Sarjapura Main Road, Dommasandra Anekal Taluka': {'zone': 'South Zone 2', 'junction': 'IbblurJunction\'', 'lat': 12.8829, 'lng': 77.7543},
    'Seshadri Road, Ayurvedic Hospital Junction': {'zone': 'Central Zone 2', 'junction': 'K R Circle', 'lat': 12.98, 'lng': 77.5737},
    'Sheshadripuram Road, Sangolli Rayanna Circle': {'zone': 'Central Zone 2', 'junction': 'KrishnaFlourMill', 'lat': 12.9846, 'lng': 77.5717},
    'Shivajinagar Road, Shivaji Nagar': {'zone': 'Central Zone 2', 'junction': 'VetenaryHospitalJunc-Shivajinagar', 'lat': 12.9872, 'lng': 77.5994},
    'Siddavanahalli Krishna Sharma Road, Sri Maramma Temple Circle': {'zone': 'West Zone 2', 'junction': 'MargosaRd-18thCrossJunc', 'lat': 13.0087, 'lng': 77.5691},
    'Silk Board Double Decker Flyover, Central Silk Board Staff Quarters': {'zone': 'South Zone 2', 'junction': 'SilkBoardJunc', 'lat': 12.9168, 'lng': 77.6214},
    'Sir CV Raman Road, Enayathulla Mehkri Circle': {'zone': 'West Zone 2', 'junction': 'MekhriCircle', 'lat': 13.0146, 'lng': 77.5835},
    'Sri Venkataranga Ayangar Road, Acharya Sri Ramanuja Circle': {'zone': 'West Zone 2', 'junction': 'Malleswaram18thCrossRd-SampigeRdJunc', 'lat': 13.0062, 'lng': 77.5712},
    'Sri Venkataranga Iyengar Road, Mill Corner Junction': {'zone': 'Central Zone 2', 'junction': 'MillCornerRd-SampigeRdJunc', 'lat': 12.9924, 'lng': 77.5714},
    'Srinivagilu Main Road, KR Garden': {'zone': 'Central Zone 1', 'junction': 'BucheryJunction', 'lat': 12.9431, 'lng': 77.622},
    'Subedar Chatram Road, Shri Rajiv Gandhi Circle': {'zone': 'Central Zone 2', 'junction': 'SubedarChatramRd near SheshadripuramPS', 'lat': 12.9896, 'lng': 77.5723},
    'Thalagattapura Road, Hosahalli South Taluka': {'zone': 'South Zone 1', 'junction': 'KonanakunteJunction(KanakapurarRd)', 'lat': 12.8745, 'lng': 77.5393},
    'Upparpet Road, Mysore Bank Circle': {'zone': 'Central Zone 2', 'junction': 'StateBankofMysoreJunc', 'lat': 12.9753, 'lng': 77.578},
    'VV Puram Road, Professor P Shivshankar Circle': {'zone': 'Central Zone 2', 'junction': 'MintoJunction', 'lat': 12.9571, 'lng': 77.574},
    'Vijayanagara Road, Binny Layout': {'zone': 'West Zone 2', 'junction': 'PuttammaChoultryNagarbhavi', 'lat': 12.9757, 'lng': 77.5411},
    'Vinoba Nagar Main Road, Narasimha Block': {'zone': 'North Zone 1', 'junction': 'Unknown', 'lat': 13.0201, 'lng': 77.6189},
    'Whitefield Main Road, HBK Layout': {'zone': 'East Zone 1', 'junction': 'HopefarmJunction', 'lat': 12.9798, 'lng': 77.7516},
    'Whitefield Road, Sadaramangala Industrial Area': {'zone': 'East Zone 1', 'junction': 'HopefarmJunction', 'lat': 12.9647, 'lng': 77.7418},
    'Wilson Garden Road, Dr Ambedkar Social Welfare Association': {'zone': 'Central Zone 2', 'junction': 'SiddapuraJunction', 'lat': 12.9486, 'lng': 77.5928},
    'Yelahanka Road, Nagarjuna Aster Park': {'zone': 'North Zone 2', 'junction': 'SandeepUnnikrishnan-Yelhanka', 'lat': 13.1007, 'lng': 77.5804},
    'Yeshwanthpura Road, Nada Prabhu Kempegowda Circle': {'zone': 'North Zone 2', 'junction': 'Unknown', 'lat': 13.034, 'lng': 77.5574},
}
